services:
  postgres:
    image: postgres:latest
    container_name: prepkeeper
    environment:
      POSTGRES_DB: prepkeeper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: star2005
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:

