from .search_tools import SEARCH_TOOLS
from .rag_tools import RAG_TOOLS
from .db_tools import DB_TOOLS

PLAN_TOOLS = SEARCH_TOOLS + DB_TOOLS
CHECKIN_TOOLS = RAG_TOOLS + DB_TOOLS
REMINDER_TOOLS = RAG_TOOLS + DB_TOOLS
REPORT_TOOLS = RAG_TOOLS + DB_TOOLS

ALL_TOOLS = SEARCH_TOOLS + RAG_TOOLS + DB_TOOLS

__all__ = [
    "SEARCH_TOOLS", "RAG_TOOLS", "DB_TOOLS",
    "PLAN_TOOLS", "CHECKIN_TOOLS", "REMINDER_TOOLS", "REPORT_TOOLS",
    "ALL_TOOLS",
]
